os:
  - linux
  - osx

compiler: gcc
language: c
sudo: require
dist: bionic

install:
  - if [ $TRAVIS_OS_NAME == osx ]; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew install cmocka;
        HOMEBREW_NO_AUTO_UPDATE=1 brew install zmq;
        git clone https://github.com/nlohmann/json.git;
        cp -a json/single_include/nlohmann /usr/local/include/;
        HOMEBREW_NO_AUTO_UPDATE=1 brew cask install oclint;
    else
        sudo apt-get install -y libcmocka-dev;
        sudo apt-get install -y libzmq3-dev;
        git clone https://github.com/nlohmann/json.git;
        sudo cp -a json/single_include/nlohmann /usr/local/include/;
    fi

script:
  - mkdir build && cd build && cmake .. -DBUILD_TESTS=on
    && make && make test && cd -
  - if [ $TRAVIS_OS_NAME == osx ]; then
        oclint-json-compilation-database -e 'tests/.*' -p build;
    fi
